name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: سحب الكود
        uses: actions/checkout@v4

      - name: بناء ملف APK داخل بيئة معزولة جاهزة
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable

      - name: رفع ملف APK كمرفق للتحميل
        uses: actions/upload-artifact@v4
        with:
          name: Nilebooks-APK
          path: bin/*.apk
